library(tidyverse)
source("data_preparation.R")

gds <- gds %>%
  select(-session, -datedig) %>%
  mutate(across(where(is.double), remove_outliers))

####### tail
## rh
tail_rh_fa <- lm(HP_tail_rh_hippo2dti_fa ~ ccitotal, gds)
summary(tail_rh_fa)
tail_rh_md <- lm(HP_tail_rh_hippo2dti_md ~ ccitotal, gds)
summary(tail_rh_md)
tail_rh_ad <- lm(HP_tail_rh_hippo2dti_ad ~ ccitotal, gds)
summary(tail_rh_ad)
tail_rh_rd <- lm(HP_tail_rh_hippo2dti_rd ~ ccitotal, gds)
summary(tail_rh_rd)
tail_rh_kfa <- lm(HP_tail_rh_hippo2dki_kfa ~ ccitotal, gds)
summary(tail_rh_kfa)
tail_rh_mk <- lm(HP_tail_rh_hippo2dki_mk ~ ccitotal, gds)
summary(tail_rh_mk)
tail_rh_ak <- lm(HP_tail_rh_hippo2dki_ak ~ ccitotal, gds)
summary(tail_rh_ak)
tail_rh_rk <- lm(HP_tail_rh_hippo2dki_rk ~ ccitotal, gds)
summary(tail_rh_rk)
## lh
tail_lh_fa <- lm(HP_tail_lh_hippo2dti_fa ~ ccitotal, gds)
summary(tail_lh_fa)
tail_lh_md <- lm(HP_tail_lh_hippo2dti_md ~ ccitotal, gds)
summary(tail_lh_md)
tail_lh_ad <- lm(HP_tail_lh_hippo2dti_ad ~ ccitotal, gds)
summary(tail_lh_ad)
tail_lh_rd <- lm(HP_tail_lh_hippo2dti_rd ~ ccitotal, gds)
summary(tail_lh_rd)
tail_lh_kfa <- lm(HP_tail_lh_hippo2dki_kfa ~ ccitotal, gds)
summary(tail_lh_kfa)
tail_lh_mk <- lm(HP_tail_lh_hippo2dki_mk ~ ccitotal, gds)
summary(tail_lh_mk)
tail_lh_ak <- lm(HP_tail_lh_hippo2dki_ak ~ ccitotal, gds)
summary(tail_lh_ak)
tail_lh_rk <- lm(HP_tail_lh_hippo2dki_rk ~ ccitotal, gds)
summary(tail_lh_rk)

##### body
## rh
body_rh_fa <- lm(HP_body_rh_hippo2dti_fa ~ ccitotal, gds)
summary(body_rh_fa)
body_rh_md <- lm(HP_body_rh_hippo2dti_md ~ ccitotal, gds)
summary(body_rh_md)
body_rh_ad <- lm(HP_body_rh_hippo2dti_ad ~ ccitotal, gds)
summary(body_rh_ad)
body_rh_rd <- lm(HP_body_rh_hippo2dti_rd ~ ccitotal, gds)
summary(body_rh_rd)
body_rh_kfa <- lm(HP_body_rh_hippo2dki_kfa ~ ccitotal, gds)
summary(body_rh_kfa)
body_rh_mk <- lm(HP_body_rh_hippo2dki_mk ~ ccitotal, gds)
summary(body_rh_mk)
body_rh_ak <- lm(HP_body_rh_hippo2dki_ak ~ ccitotal, gds)
summary(body_rh_ak)
body_rh_rk <- lm(HP_body_rh_hippo2dki_rk ~ ccitotal, gds)
summary(body_rh_rk)
## lh
body_lh_fa <- lm(HP_body_lh_hippo2dti_fa ~ ccitotal, gds)
summary(body_lh_fa)
body_lh_md <- lm(HP_body_lh_hippo2dti_md ~ ccitotal, gds)
summary(body_lh_md)
body_lh_ad <- lm(HP_body_lh_hippo2dti_ad ~ ccitotal, gds)
summary(body_lh_ad)
body_lh_rd <- lm(HP_body_lh_hippo2dti_rd ~ ccitotal, gds)
summary(body_lh_rd)
body_lh_kfa <- lm(HP_body_lh_hippo2dki_kfa ~ ccitotal, gds)
summary(body_lh_kfa)
body_lh_mk <- lm(HP_body_lh_hippo2dki_mk ~ ccitotal, gds)
summary(body_lh_mk)
body_lh_ak <- lm(HP_body_lh_hippo2dki_ak ~ ccitotal, gds)
summary(body_lh_ak)
body_lh_rk <- lm(HP_body_lh_hippo2dki_rk ~ ccitotal, gds)
summary(body_lh_rk)

##### head
## rh
head_rh_fa <- lm(HP_head_rh_hippo2dti_fa ~ ccitotal, gds)
summary(head_rh_fa)
head_rh_md <- lm(HP_head_rh_hippo2dti_md ~ ccitotal, gds)
summary(head_rh_md)
head_rh_ad <- lm(HP_head_rh_hippo2dti_ad ~ ccitotal, gds)
summary(head_rh_ad)
head_rh_rd <- lm(HP_head_rh_hippo2dti_rd ~ ccitotal, gds)
summary(head_rh_rd)
head_rh_kfa <- lm(HP_head_rh_hippo2dki_kfa ~ ccitotal, gds)
summary(head_rh_kfa)
head_rh_mk <- lm(HP_head_rh_hippo2dki_mk ~ ccitotal, gds)
summary(head_rh_mk)
head_rh_ak <- lm(HP_head_rh_hippo2dki_ak ~ ccitotal, gds)
summary(head_rh_ak)
head_rh_rk <- lm(HP_head_rh_hippo2dki_rk ~ ccitotal, gds)
summary(head_rh_rk)
## lh
head_lh_fa <- lm(HP_head_lh_hippo2dti_fa ~ ccitotal, gds)
summary(head_lh_fa)
head_lh_md <- lm(HP_head_lh_hippo2dti_md ~ ccitotal, gds)
summary(head_lh_md)
head_lh_ad <- lm(HP_head_lh_hippo2dti_ad ~ ccitotal, gds)
summary(head_lh_ad)
head_lh_rd <- lm(HP_head_lh_hippo2dti_rd ~ ccitotal, gds)
summary(head_lh_rd)
head_lh_kfa <- lm(HP_head_lh_hippo2dki_kfa ~ ccitotal, gds)
summary(head_lh_kfa)
head_lh_mk <- lm(HP_head_lh_hippo2dki_mk ~ ccitotal, gds)
summary(head_lh_mk)
head_lh_ak <- lm(HP_head_lh_hippo2dki_ak ~ ccitotal, gds)
summary(head_lh_ak)
head_lh_rk <- lm(HP_head_lh_hippo2dki_rk ~ ccitotal, gds)
summary(head_lh_rk)
